import HomeFollow from "../components/home-follow";
import HomeMain from "../components/home-main";
import Footer from "../components/footer";

export default function Home() {
  return (
    <>
      <HomeFollow></HomeFollow>
      <HomeMain></HomeMain>
      <Footer></Footer>
    </>
  );
}
export const metadata = {
  metadataBase: new URL("https://casa-dev.com"),
  alternates: {
    canonical: "/",
    languages: {
      "en-US": "/en-US",
    },
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    // 📢 OPEN GRAPH TITLE: Focus on Expertise and Strategy
    title: "Casa Dev: Strategic Digital Partner | 10+ YOE in Dev, Design, & Marketing",
    // 📢 OPEN GRAPH DESCRIPTION: Anti-AI/Strategic Value
    description:
      "Avoid technical debt from AI boilerplate. I am your strategic partner, delivering custom, hand-coded platforms built for long-term ROI and guaranteed scalability. 10+ years of holistic expertise.",
    url: "https://casa-dev.com",
    siteName: "Casa Dev",
    images: [
      {
        url: "https://casa-dev.com/images/og-image.jpg", // Update to your real OG image
        width: 1200,
        height: 630,
      },
    ],
    locale: "en_US",
    type: "website",
  },
  // 📢 MAIN TITLE: High-Value, Expert Positioning
  title:
    "Casa Dev: Code Built by an Expert, Not Generated by AI | Technical Strategy & Development",
  // 📢 MAIN DESCRIPTION: Emphasizes full expertise and strategic value
  description:
    "I am a full-stack digital partner with 10+ years in development, design, and marketing. I build clean, high-performing platforms that minimize risk and maximize long-term business ROI. Invest in a strategic foundation.",
  // 📢 KEYWORDS: New terms reflect high-value service
  keywords: [
    "strategic web development",
    "expert developer",
    "anti-AI code",
    "holistic digital partner",
    "technical strategy",
    "custom SaaS development",
    "high-ROI websites",
    "clean code",
    "minimize technical debt"
  ],
};
