import Link from "next/link";
import styles from "../app/about/about.module.scss";

export default function Services() {
  return (
    <>
      <section className={styles.page} data-scroll-section>
        <div className={styles.container}>
          <h1 className={styles.title}>Strategic Development & Digital Partnership</h1>
          <span className={styles.subtitle}>
            Code Built by an Expert, Not Generated by AI.
          </span>
          <p>
            With **10+ years of holistic expertise in development, design, and marketing**, 
            I build platforms designed to minimize risk and maximize your long-term ROI. 
            I don't offer shortcuts—I offer a strategic foundation tailored to your business goals.
          </p>
        </div>
      </section>

      <section className="home_services" data-scroll-section>
        <div className="container">
          <h2 className="title">
            Strategic Solutions: Minimized Risk, Maximized ROI
          </h2>
          <div className="services">
            {[
              {
                title: "WCAG & Risk Mitigation Compliance",
                description:
                  "Ensure your platform is legally compliant and universally accessible. My **WCAG and ADA compliance audits** are integrated with development, mitigating future legal and technical risks.",
              },
              {
                title: "Performance & Code Optimization",
                description:
                  "I go beyond basic caching to **hand-tune your codebase** for lightning-fast speeds. This ensures top-tier SEO rankings and superior conversion rates that cheap code can't achieve.",
              },
              {
                title: "Conversion-Focused UX/UI Design",
                description:
                  "I apply a **marketing-first design philosophy**. Every element is crafted to be visually stunning, on-brand, and optimized to engage high-value leads and drive conversions.",
              },
              {
                title: "Scalable Custom Web Development",
                description:
                  "Building responsive, secure, and **future-proof platforms**. From complex web applications to custom integrations, I deliver clean, documented code that scales with your business for years.",
              },
              {
                title: "Enterprise-Level CMS & Integrations",
                description:
                  "Streamline content management and complex data workflows with advanced, custom CMS solutions. Perfect for large organizations needing high efficiency, security, and specialized API connections.",
              },
              {
                title: "Strategic Platform Redesign",
                description:
                  "It's more than a facelift. I lead strategic redesigns focused on modernizing architecture, improving SEO structure, and enhancing user pathways to **achieve specific business growth targets**.",
              },
              {
                title: "Technical Debt & Maintenance Retainer",
                description:
                  "A long-term partnership to keep your digital asset secure, updated, and high-performing. This retainer service actively **minimizes technical debt** and protects your investment.",
              },
              {
                title: "Growth-Driven SEO & Digital Strategy",
                description:
                  "My **in-depth marketing expertise** ensures your platform is built to dominate search results. I optimize content, structure, and technical SEO to attract high-quality organic traffic and convert visitors.",
              },
            ].map((service, index) => (
              <div className="item" key={index}>
                <h3 className="title">
                  <span>{service.title}</span>
                </h3>
                <p>{service.description}</p>
              </div>
            ))}
          </div>
          <div className="link-widget-wrap">
            <Link
              className="btn_link btn_link--light"
              href="/contact/"
              target="_blank"
              rel="noopener"
            >
              Start Strategic Consultation
              <span>
                <svg
                  width="8"
                  height="12"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M.293 1.707 1.707.293 7.414 6l-5.707 5.707-1.414-1.414L4.585 6z"
                    fill="currentColor"
                  ></path>
                </svg>
              </span>
            </Link>
            <Link className="btn_link btn_link--light" href="/contact/">
              Talk to Me
              <span>
                <svg
                  width="8"
                  height="12"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M.293 1.707 1.707.293 7.414 6l-5.707 5.707-1.414-1.414L4.585 6z"
                    fill="currentColor"
                  ></path>
                </svg>
              </span>
            </Link>
          </div>
        </div>
      </section>

      <section className="home_skillset" data-scroll-section>
        <div className="container">
          <h4>
            The Full-Stack Advantage: Why Hire a Technical Strategist?
          </h4>
          {[
            {
              title: "10+ Years of Holistic Expertise",
              description:
                "I bring a decade of experience across **development, design, and digital marketing**, ensuring your project benefits from a truly unified strategic vision, not siloed efforts.",
            },
            {
              title: "Code Quality Over Cheap Shortcuts",
              description:
                "I deliver hand-crafted, clean code built for performance and security, eliminating the technical debt and maintenance nightmares associated with AI or cheap outsourcing.",
            },
            {
              title: "Conversion-Driven Design",
              description:
                "My design approach combines stunning aesthetics with psychological principles, ensuring every interface element is optimized to drive user action and increase your business revenue.",
            },
            {
              title: "On-Brand Strategic Platforms",
              description:
                "Your unique brand identity is translated into a scalable, custom platform that reflects your authority and acts as a powerful strategic tool, not just an online brochure.",
            },
            {
              title: "Risk-Minimizing Custom Solutions",
              description:
                "I create bespoke solutions tailored to complex requirements, guaranteeing standout results while proactively eliminating vulnerabilities and compliance risks.",
            },
            {
              title: "Long-Term Partnership & ROI Focus",
              description:
                "I commit to clear communication, ongoing strategic support, and focusing every decision on maximizing your long-term return on investment (ROI).",
            },
          ].map((skill, index) => (
            <div
              className="hover-reveal-effect canvas-reveal cfadeinup is-inview"
              key={index}
            >
              <div className="row hover-row">
                <div className="col-xl-5 col-lg-6 desc-title">
                  <h3 className="h2">{skill.title}</h3>
                </div>
                <div className="col-xl-5 col-lg-6 desc-text">
                  <span>{skill.description}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>
    </>
  );
}